### ISSUE TITLE
correction

### ISSUE THREAD

**Issue by miroslavradojevic** [jantic/UdacityDeepLearningProjects#1]
Hi,
Nice code, very helpful. Perhaps the line 93 should be:
`stddev = calculateOptimalWeightStdDev(previousNumHiddenFeatures)`
instead of
`stddev = calculateOptimalWeightStdDev(numHiddenFeatures)`

**Comment by jantic** [comment]
I double checked- you're totally right.  I even put it in the function signature to remind myself.  I'll make the correction quick (without testing...).  I don't have Tensorflow installed currently.  Thanks!  

def calculateOptimalWeightStdDev(numPreviousLayerParams):
